#!/usr/bin/bash

# Wrapper around scp for simply copying from remote to local
usage() {
    echo "$0 [options] source target"
}

{
    options=${@: 1:$#-2}
    remote_source=${@: -2:1}
    local_target=${@: -1:1}
    
    scp ${options[@]} "$user@$client:~/$remote_source" $local_target
}